// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJgIn2uCuUUJaBmAGjyW-rrUqjn_0jGj0',
    appId: '1:752276095023:web:088722d45f85b54d6ec6da',
    messagingSenderId: '752276095023',
    projectId: 'news-41a50',
    authDomain: 'news-41a50.firebaseapp.com',
    storageBucket: 'news-41a50.firebasestorage.app',
    measurementId: 'G-09XJFREZ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxAA_gFTgJQI5hXQv30LT9iHRieCBVnZI',
    appId: '1:752276095023:android:4fe88a0f99649d4d6ec6da',
    messagingSenderId: '752276095023',
    projectId: 'news-41a50',
    storageBucket: 'news-41a50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-yXz3QwGvtyUFB_qKdAZazrvvMDmtSo',
    appId: '1:752276095023:ios:7895fdeedad38fbd6ec6da',
    messagingSenderId: '752276095023',
    projectId: 'news-41a50',
    storageBucket: 'news-41a50.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0-yXz3QwGvtyUFB_qKdAZazrvvMDmtSo',
    appId: '1:752276095023:ios:7895fdeedad38fbd6ec6da',
    messagingSenderId: '752276095023',
    projectId: 'news-41a50',
    storageBucket: 'news-41a50.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3GWTCTTcpE0_mZEU0Q3S9KrUjjkSysPU',
    appId: '1:752276095023:web:b73548fdc4c31c2a6ec6da',
    messagingSenderId: '752276095023',
    projectId: 'news-41a50',
    authDomain: 'news-41a50.firebaseapp.com',
    storageBucket: 'news-41a50.firebasestorage.app',
    measurementId: 'G-255FR0BYM1',
  );
}
